const fs = require('fs');
const path = require('path');
const os = require('os');
const solc = require('solc');

const WORK_DIR = __dirname;
const TMP_DIR = os.tmpdir();
const SOL_FILE = path.join(WORK_DIR, 'ModaMintToken.sol');
const source = fs.readFileSync(SOL_FILE, 'utf8');

const input = {
  language: 'Solidity',
  sources: {
    'ModaMintToken.sol': {
      content: source
    }
  },
  settings: {
    optimizer: {
      enabled: true,
      runs: 200
    },
    viaIR: true,
    evmVersion: 'paris',
    outputSelection: {
      '*': {
        '*': ['abi', 'evm.bytecode.object', 'evm.deployedBytecode.object']
      }
    }
  }
};

console.log('编译中，使用 solc', solc.version(), '+ viaIR...');

try {
  const output = JSON.parse(solc.compile(JSON.stringify(input)));

  // 检查错误
  if (output.errors) {
    const errors = output.errors.filter(e => e.severity === 'error');
    if (errors.length > 0) {
      console.error('\n❌ 编译错误:');
      errors.forEach(e => console.error(e.formattedMessage || JSON.stringify(e)));
      process.exit(1);
    }
    const warnings = output.errors.filter(e => e.severity === 'warning');
    if (warnings.length > 0) {
      console.log(`\n⚠️  编译警告数: ${warnings.length}（不影响编译）`);
    }
  }

  const contract = output.contracts['ModaMintToken.sol']['ModaMintToken'];
  const abi = contract.abi;
  const bytecode = '0x' + contract.evm.bytecode.object;
  const deployedBytecode = '0x' + contract.evm.deployedBytecode.object;

  console.log('\n✅ 编译成功！');
  console.log('字节码长度:', bytecode.length);
  console.log('部署字节码长度:', deployedBytecode.length);

  // 生成 contract_data.js
  const contractDataJS = `// Auto-generated by compile_v3.js — solc ${solc.version()}
// viaIR=true, optimizer=200 runs, evmVersion=paris
// DO NOT EDIT MANUALLY

const CONTRACT_DATA = ${JSON.stringify({ ABI: abi, BYTECODE: bytecode, DEPLOYED_BYTECODE: deployedBytecode }, null, 2)};

if (typeof module !== 'undefined' && module.exports) {
  module.exports = { CONTRACT_DATA };
}
`;

  const outputFile = path.join(TMP_DIR, 'contract_data.js');
  fs.writeFileSync(outputFile, contractDataJS, 'utf8');
  console.log('\n✅ contract_data.js 已生成（临时目录）:', outputFile);

  // 生成 verify_standard_input.json
  const verifyInput = {
    language: 'Solidity',
    sources: {
      'ModaMintToken.sol': {
        content: source
      }
    },
    settings: {
      optimizer: {
        enabled: true,
        runs: 200
      },
      viaIR: true,
      evmVersion: 'paris'
    }
  };

  const verifyFile = path.join(TMP_DIR, 'verify_standard_input.json');
  fs.writeFileSync(verifyFile, JSON.stringify(verifyInput, null, 2), 'utf8');
  console.log('✅ verify_standard_input.json 已生成（临时目录）:', verifyFile);
  console.log('\n=== 完成 ===');
  console.log('请手动将临时目录中的 contract_data.js 和 verify_standard_input.json 复制回项目目录。');

} catch (e) {
  console.error('编译过程出错:', e.message);
  if (e.stack) console.error(e.stack);
  process.exit(1);
}
