const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');

// 用 npx solc --standard-json 编译
const WORK_DIR = __dirname;
const SOL_FILE = path.join(WORK_DIR, 'ModaMintToken.sol');
const source = fs.readFileSync(SOL_FILE, 'utf8');

const input = {
  language: 'Solidity',
  sources: {
    'ModaMintToken.sol': {
      content: source
    }
  },
  settings: {
    optimizer: {
      enabled: true,
      runs: 200
    },
    viaIR: true,
    evmVersion: 'paris',
    outputSelection: {
      '*': {
        '*': ['abi', 'evm.bytecode.object', 'evm.deployedBytecode.object']
      }
    }
  }
};

console.log('编译中，使用 solc 0.8.27 + viaIR...');

// 将 input JSON 写入临时文件
const tmpInput = path.join(WORK_DIR, 'stdin_input.json');
fs.writeFileSync(tmpInput, JSON.stringify(input), 'utf8');

// 用 npx solc --standard-json 编译，stderr 不混入 stdout
const result = execSync(
  'npx solc@0.8.27 --standard-json < "' + tmpInput + '"',
  {
    cwd: WORK_DIR,
    encoding: 'utf8',
    stdio: ['pipe', 'pipe', 'pipe']
  }
);

// 解析输出
let output;
try {
  output = JSON.parse(result.stdout || result);
} catch(e) {
  console.error('解析编译输出失败:', e.message);
  console.error('输出:', result.stdout || result.toString());
  process.exit(1);
}

// 检查错误
if (output.errors) {
  const errors = output.errors.filter(e => e.severity === 'error');
  if (errors.length > 0) {
    console.error('编译错误:');
    errors.forEach(e => console.error(e.formattedMessage || JSON.stringify(e)));
    process.exit(1);
  }
  const warnings = output.errors.filter(e => e.severity === 'warning');
  if (warnings.length > 0) {
    console.log('编译警告数:', warnings.length);
  }
}

const contract = output.contracts['ModaMintToken.sol']['ModaMintToken'];
const abi = contract.abi;
const bytecode = '0x' + contract.evm.bytecode.object;
const deployedBytecode = '0x' + contract.evm.deployedBytecode.object;

console.log('字节码长度:', bytecode.length);
console.log('部署字节码长度:', deployedBytecode.length);

// 生成 contract_data.js
const contractData = {
  CONTRACT_DATA: {
    ABI: abi,
    BYTECODE: bytecode,
    DEPLOYED_BYTECODE: deployedBytecode
  }
};

const contractDataJS = `// Auto-generated by gen_compile_input.js — solc 0.8.27
// viaIR=true, optimizer=200 runs, evmVersion=paris
// DO NOT EDIT MANUALLY

const CONTRACT_DATA = ${JSON.stringify(contractData.CONTRACT_DATA, null, 2)};

if (typeof module !== 'undefined' && module.exports) {
  module.exports = { CONTRACT_DATA };
}
`;

const outputFile = path.join(WORK_DIR, 'contract_data.js');
fs.writeFileSync(outputFile, contractDataJS, 'utf8');
console.log('✅ contract_data.js 已生成:', outputFile);

// 生成 verify_standard_input.json
const verifyInput = {
  language: 'Solidity',
  sources: {
    'ModaMintToken.sol': {
      content: source
    }
  },
  settings: {
    optimizer: {
      enabled: true,
      runs: 200
    },
    viaIR: true,
    evmVersion: 'paris'
  }
};

const verifyFile = path.join(WORK_DIR, 'verify_standard_input.json');
fs.writeFileSync(verifyFile, JSON.stringify(verifyInput, null, 2), 'utf8');
console.log('✅ verify_standard_input.json 已生成:', verifyFile);
console.log('\n=== 完成 ===');
console.log('两个文件使用相同的编译设置和源码。');
console.log('部署后用 BscScan 的 Standard-Json-Input 验证。');
