// 统一编译脚本：ModaMintToken.sol → contract_data.js + verify_standard_input.json
// 用 solc 0.8.20, viaIR=true, optimizer=200, evm=paris

const fs = require('fs');
const solc = require('solc');
const path = require('path');

const WORK_DIR = __dirname;
const SOURCE_FILE = path.join(WORK_DIR, 'ModaMintToken.sol');
const source = fs.readFileSync(SOURCE_FILE, 'utf8');

const input = {
    language: 'Solidity',
    sources: {
        'ModaMintToken.sol': {
            content: source
        }
    },
    settings: {
        optimizer: {
            enabled: true,
            runs: 200
        },
        viaIR: true,
        evmVersion: 'paris',
        outputSelection: {
            '*': {
                '*': ['abi', 'evm.bytecode.object', 'evm.deployedBytecode.object']
            }
        }
    }
};

console.log('Compiling ModaMintToken.sol with solc', solc.version());
const output = JSON.parse(solc.compile(JSON.stringify(input)));

// Check for errors
if (output.errors) {
    const errors = output.errors.filter(e => e.severity === 'error');
    if (errors.length > 0) {
        console.error('COMPILATION ERRORS:');
        errors.forEach(e => console.error(e.formattedMessage));
        process.exit(1);
    }
    const warnings = output.errors.filter(e => e.severity === 'warning');
    if (warnings.length > 0) {
        console.log('Warnings:', warnings.length);
    }
}

const contract = output.contracts['ModaMintToken.sol']['ModaMintToken'];
const abi = contract.abi;
const bytecode = '0x' + contract.evm.bytecode.object;
const deployedBytecode = '0x' + contract.evm.deployedBytecode.object;

console.log('Bytecode length:', bytecode.length);
console.log('Deployed Bytecode length:', deployedBytecode.length);

// ===== Generate contract_data.js =====
const contractData = {
    CONTRACT_DATA: {
        ABI: abi,
        BYTECODE: bytecode,
        DEPLOYED_BYTECODE: deployedBytecode
    }
};

const contractDataJS = `// Auto-generated by compile.js — solc ${solc.version()}
// viaIR=true, optimizer=200 runs, evmVersion=paris
// DO NOT EDIT MANUALLY

const CONTRACT_DATA = ${JSON.stringify(contractData.CONTRACT_DATA, null, 2)};

if (typeof module !== 'undefined' && module.exports) {
    module.exports = { CONTRACT_DATA };
}
`;

fs.writeFileSync(path.join(WORK_DIR, 'contract_data.js'), contractDataJS);
console.log('✅ contract_data.js generated');

// ===== Generate verify_standard_input.json =====
const verifyInput = {
    language: 'Solidity',
    sources: {
        'ModaMintToken.sol': {
            content: source
        }
    },
    settings: {
        optimizer: {
            enabled: true,
            runs: 200
        },
        viaIR: true,
        evmVersion: 'paris'
    }
};

fs.writeFileSync(
    path.join(WORK_DIR, 'verify_standard_input.json'),
    JSON.stringify(verifyInput, null, 2)
);
console.log('✅ verify_standard_input.json generated');
console.log('\n=== DONE ===');
console.log('Both files use identical compilation settings and source.');
console.log('Deploy with launch.html, then verify using Standard-Json-Input on BSCScan.');
